### ISSUE TITLE
Chromatic display of star

### ISSUE THREAD

**Issue by AlphaChadChan** [QuasarX1/Phys205Project#5]
Need to convert wavelength into an RGB code.

**Comment by QuasarX1** [comment]
An attempt has been implemented by @AlphaChadChan but it is currently producing luminosities of infinity.

**Comment by QuasarX1** [comment]
Assuming that the equation is correct, the function returns infinity due to the precision limit for np.exp() meaning that e**n evaluates to 1 in the formula.

**Comment by AlphaChadChan** [comment]
Using 6 reference points instead of the standard Red green and blue colours, the colour of the star is now more accurate
